#ifndef FINGER_ESP_DEFINES_H
#define FINGER_ESP_DEFINES_H

#define DEFAULT_ENERGY_REPORT_INTERVAL 30
#define INPUT_DEBOUNCE_TIME_MS 75

#define POWER_MEASUREMENT_DEADZONE_W 1.50f
#define ENERGY_MEASUREMENT_DEADZONE_W 1.50f/(2*DEFAULT_ENERGY_REPORT_INTERVAL)


#endif //FINGER_ESP_DEFINES_H
