name: webthings-shelly1pm

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install platform-io
      run: |
        pip install -U platformio

    - name: Run platformio
      run: |
        platformio run
